inherit_from: .rubocop_todo.yml

# Offense count: 1
# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 110

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 25

Style/HashSyntax:
  EnforcedStyle: hash_rockets